### ISSUE TITLE
Support authorization && securitySchema && JSONSchema && components/parameters

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/routes_to_swagger_docs#70]
## JSONSchema

An error occurred when parsing the k8s api document

```
rake aborted!
NoMethodError: undefined method `load_data' for nil:NilClass
/Users/yukihirop/RubyProjects/routes_to_swagger_docs/lib/routes_to_swagger_docs/schema/manager/file/path_item_file_manager.rb:23:in `process_deep_search_ref_recursive'
/Users/yukihirop/RubyProjects/routes_to_swagger_docs/lib/routes_to_swagger_docs/schema/manager/file/include_ref_base_file_manager.rb:37:in `block in deep_search_ref_recursive'
/Users/yukihirop/RubyProjects/routes_to_swagger_docs/lib/routes_to_swagger_docs/schema/manager/file/include_ref_base_file_manager.rb:34:in `each'
/Users/yukihirop/RubyProjects/routes_to_swagger_docs/lib/routes_to_swagger_docs/schema/manager/file/include_ref_base_file_manager.rb:34:in `deep_search_ref_recursive'
/Users/yukihirop/RubyProjects/routes_to_swagger_docs/lib/routes_to_swagger_docs/schema/manager/file/path_item_file_manager.rb:33:in `process_deep_search_ref_recursive'
```

JSONSchema could not be parsed

```
"io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps": {
                "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).",
                "properties": {
                    "$ref": {
                        "type": "string"
                    },
                    "$schema": {
                        "type": "string"
                    },
                    "additionalItems": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrBool"
                    },
                    "additionalProperties": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrBool"
                    },
                    "allOf": {
                        "items": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "array"
                    },
                    "anyOf": {
                        "items": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "array"
                    },
                    "default": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
                    },
                    "definitions": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "object"
                    },
                    "dependencies": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrStringArray"
                        },
                        "type": "object"
                    },
                    "description": {
                        "type": "string"
                    },
                    "enum": {
                        "items": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
                        },
                        "type": "array"
                    },
                    "example": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON"
                    },
                    "exclusiveMaximum": {
                        "type": "boolean"
                    },
                    "exclusiveMinimum": {
                        "type": "boolean"
                    },
                    "externalDocs": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.ExternalDocumentation"
                    },
                    "format": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "items": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaPropsOrArray"
                    },
                    "maxItems": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "maxLength": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "maxProperties": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "maximum": {
                        "format": "double",
                        "type": "number"
                    },
                    "minItems": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "minLength": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "minProperties": {
                        "format": "int64",
                        "type": "integer"
                    },
                    "minimum": {
                        "format": "double",
                        "type": "number"
                    },
                    "multipleOf": {
                        "format": "double",
                        "type": "number"
                    },
                    "not": {
                        "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                    },
                    "nullable": {
                        "type": "boolean"
                    },
                    "oneOf": {
                        "items": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "array"
                    },
                    "pattern": {
                        "type": "string"
                    },
                    "patternProperties": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "object"
                    },
                    "properties": {
                        "additionalProperties": {
                            "$ref": "#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"
                        },
                        "type": "object"
                    },
                    "required": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array"
                    },
                    "title": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "uniqueItems": {
                        "type": "boolean"
                    },
                    "x-kubernetes-embedded-resource": {
                        "description": "x-kubernetes-embedded-resource defines that the value is an embedded Kubernetes runtime.Object, with TypeMeta and ObjectMeta. The type must be object. It is allowed to further restrict the embedded object. kind, apiVersion and metadata are validated automatically. x-kubernetes-preserve-unknown-fields is allowed to be true, but does not have to be if the object is fully specified (up to kind, apiVersion, metadata).",
                        "type": "boolean"
                    },
                    "x-kubernetes-int-or-string": {
                        "description": "x-kubernetes-int-or-string specifies that this value is either an integer or a string. If this is true, an empty type is allowed and type as child of anyOf is permitted if following one of the following patterns:\n\n1) anyOf:\n   - type: integer\n   - type: string\n2) allOf:\n   - anyOf:\n     - type: integer\n     - type: string\n   - ... zero or more",
                        "type": "boolean"
                    },
                    "x-kubernetes-list-map-keys": {
                        "description": "x-kubernetes-list-map-keys annotates an array with the x-kubernetes-list-type `map` by specifying the keys used as the index of the map.\n\nThis tag MUST only be used on lists that have the \"x-kubernetes-list-type\" extension set to \"map\". Also, the values specified for this attribute must be a scalar typed field of the child structure (no nesting is supported).",
                        "items": {
                            "type": "string"
                        },
                        "type": "array"
                    },
                    "x-kubernetes-list-type": {
                        "description": "x-kubernetes-list-type annotates an array to further describe its topology. This extension must only be used on lists and may have 3 possible values:\n\n1) `atomic`: the list is treated as a single entity, like a scalar.\n     Atomic lists will be entirely replaced when updated. This extension\n     may be used on any type of list (struct, scalar, ...).\n2) `set`:\n     Sets are lists that must not have multiple items with the same value. Each\n     value must be a scalar (or another atomic type).\n3) `map`:\n     These lists are like maps in that their elements have a non-index key\n     used to identify them. Order is preserved upon merge. The map tag\n     must only be used on a list with elements of type object.\nDefaults to atomic for arrays.",
                        "type": "string"
                    },
                    "x-kubernetes-preserve-unknown-fields": {
                        "description": "x-kubernetes-preserve-unknown-fields stops the API server decoding step from pruning fields which are not specified in the validation schema. This affects fields recursively, but switches back to normal pruning behaviour if nested properties or additionalProperties are specified in the schema. This can either be true or undefined. False is forbidden.",
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
```

The value for `$ref` only expected `#/components/schemas` and `#/components/requestBodies`

**Comment by yukihirop** [comment]
```
[6] pry(#<RoutesToSwaggerDocs::Schema::PathItemFileManager>)> self.instance_variable_get(:@original_path)
=> "/Users/yukihirop/RubyProjects/routes_to_swagger_docs/example-423/swagger_docs/src/paths/apiextensions_v1.yml"

[7] pry(#<RoutesToSwaggerDocs::Schema::PathItemFileManager>)> self.instance_variable_get(:@path_type)
=> :full

[8] pry(#<RoutesToSwaggerDocs::Schema::PathItemFileManager>)> self.instance_variable_get(:@relative_save_file_path)
=> "/Users/yukihirop/RubyProjects/routes_to_swagger_docs/example-423/swagger_docs/src/paths/apiextensions_v1.yml"

[9] pry(#<RoutesToSwaggerDocs::Schema::PathItemFileManager>)> self.save_file_path
=> "/Users/yukihirop/RubyProjects/routes_to_swagger_docs/example-423/swagger_docs/src/paths/apiextensions_v1.yml"

[10] pry(#<RoutesToSwaggerDocs::Schema::PathItemFileManager>)> YAML.load_file(save_file_path)
```
